### ISSUE TITLE
Missing complex tests/rules for scalar functions

### ISSUE THREAD

**Issue by sethaxen** [JuliaDiff/ChainRules.jl#215]
Scalar functions with general rules but no complex tests:
- [ ] `identity`
- [ ] `one`
- [ ] `zero`
- [ ] `deg2rad`
- [ ] `rad2deg`
- [x] `abs2` (handled by #196)
- [ ] `+`
- [ ] `-`
- [ ] `/`
- [ ] `\`
- [ ] `^`
- [ ] `inv`
- [ ] `muladd`
- [ ] `sqrt`
- [x] `sign` (handled by #211)
- [ ] `sincos`
- [ ] `exp2`
- [ ] `exp10`
- [ ] `expm1`
- [ ] `log`
- [ ] `log2`
- [ ] `log10`
- [ ] `log1p`

Scalar functions defined/tested on reals that can be generalized to/tested on complex:
- [ ] `real`
- [ ] `imag`
- [ ] `adjoint`
- [ ] `hypot`
- [ ] `exp`
- [x] `abs` (handled by #196)
- [x] `conj` (handled by #196)
- [x] `angle` (handled by #196)
